CREATE TABLE FACULTY (
    ID BIGSERIAL PRIMARY KEY,
    IDENT VARCHAR(30) NOT NULL
);

CREATE TABLE ROLES (
    ID BIGSERIAL PRIMARY KEY,
    IDENT VARCHAR(50) NOT NULL
);

CREATE TABLE STAFF (
    ID BIGSERIAL PRIMARY KEY,
    IDENT CHAR(2) NOT NULL
);

CREATE TYPE LANG AS ENUM('ENGLISH | ANGLAIS', 'FRENCH | FRANÇAIS', 'BOTH | LES DEUX');
CREATE TYPE STATION AS ENUM('0', '1', '2', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16');

CREATE TABLE JOB (
    ID BIGSERIAL PRIMARY KEY,
    FNAME VARCHAR(20) NOT NULL,
    LNAME VARCHAR(20) NOT NULL,
    TODAY TIMESTAMP NOT NULL,
    FACULTY_ID INT REFERENCES FACULTY(ID) NOT NULL,
    ROLES_ID INT REFERENCES ROLES(ID) NOT NULL,
    LANGUANGE LANG,
    STATION_ID STATION,
    ASSISTED_BY INT REFERENCES STAFF(ID),
    ASSISSTED BOOLEAN NOT NULL DEFAULT FALSE,
    USER_DESCRIPTION TEXT NOT NULL
);