CREATE TABLE LAB2019_SCHEDULER.FACULTY (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IDENT VARCHAR(30) NOT NULL
);

CREATE TABLE LAB2019_SCHEDULER.ROLES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IDENT VARCHAR(50) NOT NULL
);

CREATE TABLE LAB2019_SCHEDULER.STAFF (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IDENT CHAR(2) NOT NULL
);

CREATE TABLE LAB2019_SCHEDULER.SOFTWARE(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IDENT VARCHAR(50) NOT NULL
);

CREATE TABLE LAB2019_SCHEDULER.TOPICS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SOFTWARE_ID INT REFERENCES SOFTWARE(ID),
    PROB TEXT NOT NULL
);

CREATE TABLE LAB2019_SCHEDULER.SUB_TOPICS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TOPIC_ID INT REFERENCES TOPICS(ID),
    SUB_TOPIC TEXT NOT NULL
);

-- CREATE TYPE LANG AS ENUM('ENGLISH | ANGLAIS', 'FRENCH | FRANÇAIS', 'BOTH | LES DEUX');
-- CREATE TYPE STATION AS ENUM('1', '2', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16');

CREATE TABLE LAB2019_SCHEDULER.JOB (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FNAME VARCHAR(20) NOT NULL,
    LNAME VARCHAR(20) NOT NULL,
    TODAY TIMESTAMP NOT NULL,
    FACULTY_ID INT REFERENCES  FACULTY(ID),
    ROLES_ID INT REFERENCES ROLES(ID),
    LANGUAGE ENUM('ENGLISH | ANGLAIS', 'FRENCH | FRANÇAIS', 'BOTH | LES DEUX'),
    STATION_ID ENUM('1', '2', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16'),
    ASSISTED_BY INT REFERENCES STAFF(ID),
    ASSISSTED BOOLEAN NOT NULL DEFAULT FALSE,
    USER_DESCRIPTION TEXT NOT NULL,
    PROBLEMS JSON NOT NULL,
    CONTACT BOOLEAN NOT NULL DEFAULT FALSE
);